# SPDX-FileCopyrightText: 2020 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

[package]
name = "deploy-rs"
version = "0.1.0"
authors = ["notgne2 <gen2@gen2.space>", "Serokell <hi@serokell.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
tokio = { version = "0.2.22", features = [ "full" ] }
serde_json = "1.0.48"
serde_derive = "1.0.104"
serde = "1.0.104"
merge = "0.1.0"
whoami = "0.9.0"
log = "0.4"
pretty_env_logger = "0.4"
inotify = "0.8"
futures-util = "0.3.6"
fork = "0.1"

[[bin]]
name = "deploy"
path = "src/main.rs"

[[bin]]
name = "activate"
path = "src/activate.rs"